/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Commodity {
  'ticker' : string,
  'name' : string,
  'description' : string,
  'volume' : number,
  'week52Low' : number,
  'category' : string,
  'week52High' : number,
  'price' : number,
  'changePercent' : number,
}
export interface Company {
  'ticker' : string,
  'marketCap' : number,
  'name' : string,
  'description' : string,
  'sector' : string,
  'week52Low' : number,
  'week52High' : number,
  'price' : number,
  'changePercent' : number,
}
export interface MarketIndex {
  'value' : number,
  'name' : string,
  'changeAmount' : number,
  'changePercent' : number,
  'symbol' : string,
}
export interface UserProfile {
  'name' : string,
  'description' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommodities' : ActorMethod<[], Array<Commodity>>,
  'getCommoditiesByCategory' : ActorMethod<[], Array<Commodity>>,
  'getEquities' : ActorMethod<[], Array<Company>>,
  'getEquitiesBySector' : ActorMethod<[], Array<Company>>,
  'getInstrumentDetail' : ActorMethod<
    [string],
    { 'company' : Company } |
      { 'commodity' : Commodity }
  >,
  'getMarketIndices' : ActorMethod<[], Array<MarketIndex>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeStaticData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];