/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Commodity = IDL.Record({
  'ticker' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'volume' : IDL.Float64,
  'week52Low' : IDL.Float64,
  'category' : IDL.Text,
  'week52High' : IDL.Float64,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const Company = IDL.Record({
  'ticker' : IDL.Text,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sector' : IDL.Text,
  'week52Low' : IDL.Float64,
  'week52High' : IDL.Float64,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const MarketIndex = IDL.Record({
  'value' : IDL.Float64,
  'name' : IDL.Text,
  'changeAmount' : IDL.Float64,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommodities' : IDL.Func([], [IDL.Vec(Commodity)], ['query']),
  'getCommoditiesByCategory' : IDL.Func([], [IDL.Vec(Commodity)], ['query']),
  'getEquities' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getEquitiesBySector' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getInstrumentDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'company' : Company, 'commodity' : Commodity })],
      ['query'],
    ),
  'getMarketIndices' : IDL.Func([], [IDL.Vec(MarketIndex)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeStaticData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Commodity = IDL.Record({
    'ticker' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'volume' : IDL.Float64,
    'week52Low' : IDL.Float64,
    'category' : IDL.Text,
    'week52High' : IDL.Float64,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const Company = IDL.Record({
    'ticker' : IDL.Text,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sector' : IDL.Text,
    'week52Low' : IDL.Float64,
    'week52High' : IDL.Float64,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const MarketIndex = IDL.Record({
    'value' : IDL.Float64,
    'name' : IDL.Text,
    'changeAmount' : IDL.Float64,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommodities' : IDL.Func([], [IDL.Vec(Commodity)], ['query']),
    'getCommoditiesByCategory' : IDL.Func([], [IDL.Vec(Commodity)], ['query']),
    'getEquities' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getEquitiesBySector' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getInstrumentDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'company' : Company, 'commodity' : Commodity })],
        ['query'],
      ),
    'getMarketIndices' : IDL.Func([], [IDL.Vec(MarketIndex)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeStaticData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };